site/ask/ask/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('qa.urls'))
]

site/ask/qa/urls.py
from django.conf.urls import url
from . import views

app_name = "qa"

urlpatterns = [
    url("^$", views.IndexView.as_view(), name="index"),
    url("^login/$", views.log_in, name="login"),
    url("^signup/$", views.signup, name="signup"),
    url("^question/(?P<question_id>\d+)/$", views.question, name="question"),
    url("^ask/$", views.ask, name="ask"),
    url("^popular/$", views.PopularView.as_view(), name="popular"),
    url("^new/$", views.test, name="new")
]

site/ask/qa/models.py
from django.db import models
from django.contrib.auth.models import User as auth_models_User


# Create your models here.
class QuestionManager(models.Manager):
    @staticmethod
    def new():
        data = Question.objects.raw(
            "SELECT * FROM qa_question ORDER BY added_at DESC")

        return tuple(data)

    @staticmethod
    def popular():
        data = Question.objects.raw(
            "SELECT * FROM qa_question ORDER BY rating DESC")

        return tuple(data)


class Question(models.Model):
    title = models.CharField(max_length=255)
    text = models.TextField()
    added_at = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)
    author = models.ForeignKey(auth_models_User, on_delete=models.PROTECT)
    likes = models.ManyToManyField(auth_models_User, related_name="likes")
    objects = QuestionManager()

    def __str__(self):
        return "{}".format(self.title)

    class Meta:
        ordering = ["-rating"]


class Answer(models.Model):
    text = models.TextField()
    added_at = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey(Question, on_delete=models.PROTECT)
    author = models.ForeignKey(auth_models_User, on_delete=models.PROTECT)

    def __str__(self):
        return "{} answers to {}".format(self.author.username,
                                         self.question.title)

site/ask/qa/forms.py
#!/usr/bin/env python3
# coding=utf-8


from django import forms
from django.forms.widgets import HiddenInput
from django.contrib.auth.models import User
from .models import Question, Answer


class AskForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ("title", "text")


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ("text", "question")

        widgets = {
            "question": HiddenInput()
        }

        labels = {
            "text": u"Your Answer"
        }


class SignupForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("username", "email", "password")

site/ask/qa/views.py
from django.http import HttpResponse, HttpRequest, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.contrib.auth.models import User as auth_models_User
from django.contrib.auth import authenticate, login
from django.views import generic
from django.core.exceptions import ObjectDoesNotExist
from .models import Question, Answer
from .forms import AskForm, AnswerForm, SignupForm


# Create your views here.
def test(request, *args, **kwargs):
    return HttpResponse("OK")


class IndexView(generic.ListView):
    model = Question
    template_name = "qa/base.html"
    context_object_name = "question_list"
    paginate_by = 10

    def get_queryset(self):
        return Question.objects.order_by("-added_at")


class PopularView(IndexView):
    def get_queryset(self):
        return Question.objects.order_by("-rating", "-added_at")


def _generate_test_user():
    try:
        stub_user = auth_models_User.objects.get(username="x")
    except ObjectDoesNotExist:
        stub_user = auth_models_User.objects.create_user(
            username="x", email="x@x.x", password="y")

    return stub_user


def question(request: HttpRequest, question_id: int):
    req_question = get_object_or_404(Question, id=question_id)
    related_answers = Answer.objects.all().order_by("added_at")

    if request.method == "POST":
        form = AnswerForm(request.POST)

        if form.is_valid():
            # save new form
            new_answer = form.save(commit=False)
            new_answer.author = request.user
            new_answer.save()

            return HttpResponseRedirect(
                reverse("qa:question", args=[question_id]))
    else:
        form = AnswerForm(initial={"question": question_id})

    return render(
        request,
        "qa/question.html",
        context={
            "question": req_question,
            "answers": related_answers.filter(question=req_question),
            "form": form
        })


def ask(request: HttpRequest):
    if request.method == "POST":
        form = AskForm(request.POST)

        if form.is_valid():
            # save new form
            new_question = form.save(commit=False)
            new_question.author = request.user
            new_question.save()
            # redirect to a new question page
            return HttpResponseRedirect(
                reverse("qa:question", args=[new_question.id]))
    else:
        # render empty form
        form = AskForm()

    return render(request, "qa/ask.html", {"form": form})


def signup(request: HttpRequest):
    if request.method == "POST":
        form = SignupForm(request.POST)

        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(new_user.password)
            new_user.save()
            # get plain text password from request
            password = request.POST["password"]

            user = authenticate(
                request, username=new_user.username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)

                    return HttpResponseRedirect(reverse("qa:index"))
    else:
        form = SignupForm()

    return render(request, "qa/signup.html", {"form": form})


def log_in(request: HttpRequest):
    username = ""
    error = ""

    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)

                return HttpResponseRedirect(reverse("qa:index"))
            else:
                error = u"User inactive"
        else:
            error = u"Wrong user name or password"

    return render(request, "qa/login.html", {"username": username, "error": error})

site/ask/qa/templates/qa/ask.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Top Asked questions">
    <title>Title</title>
</head>
<body>
<p>Ask your question</p>
<form action="{% url "qa:ask" %}" method="post">
    {% csrf_token %}
    {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {% if not field.is_hidden %}
                {{ field.label_tag }}
            {% endif %}
            {{ field }}
            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
    {% endfor %}
    <p><input type="submit" value="Ask"></p>
</form>
</body>
</html>

site/ask/qa/templates/qa/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Top Asked questions">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css" />
    <title>{% block title %}Ask Question{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="/">Ask Questions</a>
    
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href={% url "qa:index" %}>Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href={% url "qa:popular" %}>Popular</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href={% url "qa:ask" %}>Ask</a>
                </li>
            </ul>
        </div>

        <a class="btn btn-primary ml-2" href="{% url "qa:login" %}" role="button">Log in</a>
        <a class="btn btn-outline-success ml-2" href="{% url "qa:signup" %}" role="button">Sign up</a>
    </nav>
    {% block content %}
    <div id="content" class="container">
        {% if question_list %}
        <ul>
        {% for question in question_list %}
            <li><a href="{% url 'qa:question' question.id %}">{{ question.title }}</a></li>
        {% endfor %}
        </ul>
        {% endif %}
    </div>

    {% if is_paginated %}
    <div id="switch-page" class="container">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
        {% endif %}
    </div>
    {% endif %}
    {% endblock %}

    <script src="/js/bootstrap.min.js" />
</body>
</html>

site/ask/qa/templates/qa/login.html
{% extends "qa/base.html" %}

{% block title %}
Log in
{% endblock %}

{% block content %}
    <div class="container">
        <form action="{% url "qa:login" %}" method="post">
            {% csrf_token %}
            {% if error %}
                <div class="row justify-content-lg-center">
                <div class="alert alert-danger col-4" role="alert">
                    {{ error }}
                </div>
                </div>
            {% endif %}
            <div class="row justify-content-lg-center">
                <div class="form-group col-4">
                    <label for="id_login">Login:</label>
                    <input type="text" name="username" class="form-control" id="id_username" value="{{ username }}"/>
                </div>
            </div>
           <div class="row justify-content-lg-center">
                <div class="form-group col-4">
                    <label for="id_password">Password:</label>
                    <input type="password" name="password" class="form-control" id="id_password"/>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 offset-4">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

site/ask/qa/templates/qa/question.html
{% extends "qa/base.html" %}
{% block title %}{{ question.title }}{% endblock %}

{% block content %}
    <div id="content" class="container">
        <div id="question-title">
            <h1>{{ question.title }}</h1>
        </div>
        {{ question.text }}
    </div>
    <div id="ans_form" class="container">
        <form action="{% url "qa:question" question_id=question.id %}" method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="field_wrap">
                    {{ field.errors }}
                    {% if not field.is_hidden %}{{ field.label_tag }}{% endif %}
                    {{ field }}
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
            {% endfor %}
            <p><input type="submit" value="Answer" /></p>
        </form>
    </div>
    {% if answers %}
    <div id="answers" class="container">
        {% for answer in answers %}
            <div class="answer">
                {{ answer.text }}
            </div>
        {% endfor %}
    </div>
    {% endif %}
{% endblock %}

site/ask/qa/templates/qa/signup.html
{% extends "qa/base.html" %}

{% block title %}
Sign Up
{% endblock %}

{% block content %}
    <div class="container">
        <form action="{% url "qa:signup" %}" method="post">
            {% csrf_token %}
            <div class="row justify-content-lg-center">
                <div class="form-group col-4">
                    {{ form.username.errors }}
                    {{ form.username.label_tag }}
                    <input type="text" name="{{ form.username.name }}" required class="form-control" id="{{ form.username.id_for_label }}"/>
                    {{ field }}
                </div>
            </div>
            <div class="row justify-content-lg-center">
                <div class="form-group col-4">
                    {{ form.email.errors }}
                    {{ form.email.label_tag }}
                    <input type="email" name="{{ form.email.name }}" class="form-control" id="{{ form.email.id_for_label }}"/>
                </div>
            </div>
            <div class="row justify-content-lg-center">
                <div class="form-group col-4">
                    {{ form.password.errors }}
                    {{ form.password.label_tag }}
                    <input type="text" name="{{ form.password.name }}" required class="form-control" id="{{ form.password.id_for_label }}"/>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 offset-4">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}